[package]
name = "ZenBackend"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky = "0.10.0"
clap = { version = "4.5.36", features = ["derive"] }
colored = "3.0.0"
num = "0.4.3"
pest = "2.8.0"
pest_derive = "2.8.0"
