[package]
name = "ZenBackend"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky = "0.9.0"
clap = { version = "4.5.36", features = ["derive"] }
colored = "3.0.0"
const_format = "0.2.34"
ctrlc = "3.4.6"
defer = "0.2.1"
logos = "0.15.0"
num = "0.4.3"
rand = "0.9.1"
regex = "1.11.1"
